const now = Date.now();
const minutesAgo = (m) => new Date(now - m * 60000).toISOString();

export const initialDrivers = [];

export const initialStoreSettings = {
  id: 'main_store',
  store_name: 'Store Central Hub (Ghaziabad)',
  latitude: 28.6692,
  longitude: 77.4538,
  radius_meters: 150,
  updated_at: new Date().toISOString()
};

export const initialDriverLocations = [];

export const initialOrders = [
  {
    id: 'ord-0001',
    order_number: 'JJ-1001',
    amount: 350.0,
    address: 'Plot 42, Green Avenue, Sector 14',
    landmark: 'Near Mother Dairy Booth',
    customer_phone: '9810012345',
    customer_name: 'Vikas Gupta',
    assigned_driver_id: null,
    driver_id: null,
    driver_name: 'Unassigned',
    status: 'Pending',
    latitude: 28.6620,
    longitude: 77.4480,
    accepted_at: minutesAgo(20),
    estimated_minutes: 25,
    payment_method: null,
    payment_proof_url: null,
    delivery_proof_url: null,
    delivered_at: null,
    notes: 'Please ring the bell twice',
    created_at: minutesAgo(45),
  },
  {
    id: 'ord-0002',
    order_number: 'JJ-1002',
    amount: 520.0,
    address: 'Flat 304, Royal Palms Heights, Tower B',
    landmark: 'Opposite City Mall Gate 2',
    customer_phone: '9871198765',
    customer_name: 'Pooja Verma',
    assigned_driver_id: null,
    driver_id: null,
    driver_name: 'Unassigned',
    status: 'Pending',
    latitude: 28.6820,
    longitude: 77.4610,
    accepted_at: null,
    estimated_minutes: 18,
    payment_method: null,
    payment_proof_url: null,
    delivery_proof_url: null,
    delivered_at: null,
    notes: 'Leave with guard if unavailable',
    created_at: minutesAgo(15),
  },
  {
    id: 'ord-0003',
    order_number: 'JJ-1003',
    amount: 280.0,
    address: 'House 18, Block C, Shanti Vihar',
    landmark: 'Behind Community Center',
    customer_phone: '9955443322',
    customer_name: 'Anil Mehra',
    assigned_driver_id: null,
    driver_id: null,
    driver_name: 'Unassigned',
    status: 'Pending',
    latitude: 28.6740,
    longitude: 77.4390,
    accepted_at: null,
    estimated_minutes: 14,
    payment_method: null,
    payment_proof_url: null,
    delivery_proof_url: null,
    delivered_at: null,
    notes: 'Call before arriving',
    created_at: minutesAgo(10),
  },
  {
    id: 'ord-0004',
    order_number: 'JJ-1004',
    amount: 410.0,
    address: 'Shop 12, Main Market, Phase 2',
    landmark: 'Next to Apollo Pharmacy',
    customer_phone: '9812300000',
    customer_name: 'Deepak Sethi',
    assigned_driver_id: null,
    driver_id: null,
    driver_name: 'Unassigned',
    status: 'Pending',
    latitude: 28.6590,
    longitude: 77.4690,
    accepted_at: null,
    estimated_minutes: 22,
    payment_method: null,
    payment_proof_url: null,
    delivery_proof_url: null,
    delivered_at: null,
    notes: '2 cans of 20L water required',
    created_at: minutesAgo(5),
  },
  {
    id: 'ord-0005',
    order_number: 'JJ-1000',
    amount: 720.0,
    address: 'B-44, Surya Enclave',
    landmark: 'Near Water Tank',
    customer_phone: '9811122233',
    customer_name: 'Rajesh Tyagi',
    assigned_driver_id: null,
    driver_id: null,
    driver_name: 'Unassigned',
    status: 'Delivered',
    latitude: 28.6650,
    longitude: 77.4520,
    accepted_at: minutesAgo(120),
    estimated_minutes: 20,
    delivered_at: minutesAgo(104), // Took 16 mins (4 mins early)
    payment_method: 'UPI',
    payment_proof_url: null,
    delivery_proof_url: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=500&auto=format&fit=crop&q=60',
    notes: 'Paid online',
    created_at: minutesAgo(130),
  },
  {
    id: 'ord-0006',
    order_number: 'JJ-0999',
    amount: 360.0,
    address: 'C-102, Silver Oak Apartments',
    landmark: 'Sector 62 Cross Road',
    customer_phone: '9822233344',
    customer_name: 'Sunita Rao',
    assigned_driver_id: null,
    driver_id: null,
    driver_name: 'Unassigned',
    status: 'Delivered',
    latitude: 28.6680,
    longitude: 77.4580,
    accepted_at: minutesAgo(240),
    estimated_minutes: 15,
    delivered_at: minutesAgo(218), // Took 22 mins (7 mins late)
    payment_method: 'Cash',
    payment_proof_url: null,
    delivery_proof_url: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=500&auto=format&fit=crop&q=60',
    notes: 'Cash collected',
    created_at: minutesAgo(250),
  },
  {
    id: 'ord-0007',
    order_number: 'JJ-0998',
    amount: 480.0,
    address: 'Shop 8, Navrang Plaza',
    landmark: 'Opposite State Bank ATM',
    customer_phone: '9833344455',
    customer_name: 'Kavita Joshi',
    assigned_driver_id: null,
    driver_id: null,
    driver_name: 'Unassigned',
    status: 'Delivered',
    latitude: 28.6710,
    longitude: 77.4490,
    accepted_at: minutesAgo(180),
    estimated_minutes: 18,
    delivered_at: minutesAgo(165), // Took 15 mins (3 mins early)
    payment_method: 'Cash',
    payment_proof_url: null,
    delivery_proof_url: null,
    notes: 'Doorstep cash payment',
    created_at: minutesAgo(190),
  },
  {
    id: 'ord-0008',
    order_number: 'JJ-0997',
    amount: 600.0,
    address: 'House 5, Model Town Extension',
    landmark: 'Near DAV Public School',
    customer_phone: '9844455566',
    customer_name: 'Manish Pandey',
    assigned_driver_id: null,
    driver_id: null,
    driver_name: 'Unassigned',
    status: 'Delivered',
    latitude: 28.6640,
    longitude: 77.4510,
    accepted_at: minutesAgo(300),
    estimated_minutes: 12,
    delivered_at: minutesAgo(288), // Took 12 mins (on time)
    payment_method: 'UPI',
    payment_proof_url: null,
    delivery_proof_url: null,
    notes: 'Smooth delivery',
    created_at: minutesAgo(310),
  },
  {
    id: 'ord-0009',
    order_number: 'JJ-1005',
    amount: 450.0,
    address: 'A-204, Ganga Heights, Sector 12',
    landmark: 'Opposite Community Hall',
    customer_phone: '9876501234',
    customer_name: 'Rohit Verma',
    assigned_driver_id: null,
    driver_id: null,
    driver_name: 'Unassigned',
    status: 'Pending',
    latitude: null,
    longitude: null,
    accepted_at: null,
    estimated_minutes: 20,
    payment_method: null,
    payment_proof_url: null,
    delivery_proof_url: null,
    delivered_at: null,
    notes: 'New customer, doorstep location not pinned yet',
    created_at: minutesAgo(8),
  },
  {
    id: 'ord-0010',
    order_number: 'JJ-0995',
    amount: 350.0,
    address: 'Plot 42, Green Avenue, Sector 14',
    landmark: 'Near Mother Dairy Booth',
    customer_phone: '9810012345',
    customer_name: 'Vikas Gupta',
    assigned_driver_id: null,
    driver_id: null,
    driver_name: 'Unassigned',
    status: 'Delivered',
    latitude: 28.6620,
    longitude: 77.4480,
    accepted_at: minutesAgo(420),
    estimated_minutes: 18,
    delivered_at: minutesAgo(405),
    payment_method: 'UPI',
    payment_proof_url: null,
    delivery_proof_url: null,
    notes: 'Repeat customer order',
    created_at: minutesAgo(430),
  },
];

export const initialProducts = [
  {
    id: 'prod-001',
    name: '20L RO Purified Water Jar',
    price: 50.0,
    unit: '20L Can',
    image_url: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?w=300&auto=format&fit=crop&q=80',
    in_stock: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'prod-002',
    name: '20L Premium Mineral Water Can',
    price: 90.0,
    unit: '20L Can',
    image_url: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=300&auto=format&fit=crop&q=80',
    in_stock: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'prod-003',
    name: '1L Packaged Water (Box of 12)',
    price: 180.0,
    unit: '12x 1L Pack',
    image_url: 'https://images.unsplash.com/photo-1564419320461-6870880221ad?w=300&auto=format&fit=crop&q=80',
    in_stock: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'prod-004',
    name: '500ml Bottled Water (Box of 24)',
    price: 240.0,
    unit: '24x 500ml Pack',
    image_url: 'https://images.unsplash.com/photo-1523362628745-0c100150b504?w=300&auto=format&fit=crop&q=80',
    in_stock: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'prod-005',
    name: 'Manual Water Dispenser Hand Pump',
    price: 120.0,
    unit: '1 Piece',
    image_url: 'https://images.unsplash.com/photo-1589365278144-c9e705f843ba?w=300&auto=format&fit=crop&q=80',
    in_stock: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'prod-006',
    name: 'Countertop Water Jar Tap & Stand',
    price: 280.0,
    unit: '1 Set',
    image_url: 'https://images.unsplash.com/photo-1584905066893-7d5c142ba4e1?w=300&auto=format&fit=crop&q=80',
    in_stock: true,
    created_at: new Date().toISOString()
  }
];

export const initialAddressBook = [
  {
    id: 'addr-001',
    name: 'Vikas Gupta',
    phone: '9810012345',
    address: 'Plot 42, Green Avenue, Sector 14',
    landmark: 'Near Mother Dairy Booth',
    latitude: 28.6620,
    longitude: 77.4480,
    created_at: new Date().toISOString()
  },
  {
    id: 'addr-002',
    name: 'Pooja Verma',
    phone: '9871198765',
    address: 'Flat 304, Royal Palms Heights, Tower B',
    landmark: 'Opposite City Mall Gate 2',
    latitude: 28.6740,
    longitude: 77.4610,
    created_at: new Date().toISOString()
  },
  {
    id: 'addr-003',
    name: 'Rajesh Sharma',
    phone: '9818812345',
    address: 'Shop 12, Main Market, Raj Nagar',
    landmark: 'Behind SBI Branch',
    latitude: 28.6810,
    longitude: 77.4420,
    created_at: new Date().toISOString()
  },
  {
    id: 'addr-004',
    name: 'Anita Devi',
    phone: '9910045678',
    address: 'B-15, Kavi Nagar, C-Block',
    landmark: 'Near Diamond Palace',
    latitude: 28.6550,
    longitude: 77.4560,
    created_at: new Date().toISOString()
  },
  {
    id: 'addr-005',
    name: 'Sanjay Malik',
    phone: '9899123456',
    address: 'House 88, Shanti Kunj, Vasundhara Sector 3',
    landmark: 'Near Bal Bharti School',
    latitude: 28.6680,
    longitude: 77.3850,
    created_at: new Date().toISOString()
  }
];

