export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const apiKey = process.env.GEMINI_API_KEY || process.env.VITE_GEMINI_API_KEY;
  if (!apiKey) {
    return res.status(500).json({ error: 'GEMINI_API_KEY is not configured on the server.' });
  }

  try {
    const { imageBase64, mimeType } = req.body;
    if (!imageBase64) {
      return res.status(400).json({ error: 'Missing imageBase64 in request body' });
    }

    const cleanBase64 = imageBase64.replace(/^data:image\/\w+;base64,/, '');

    const prompt = `Analyze this handwritten order slip or invoice photo carefully. Extract the order details into this EXACT raw JSON structure (do not wrap in markdown or backticks):
{
  "customer_name": "string or empty",
  "customer_phone": "string or empty",
  "delivery_address": "string or empty",
  "landmark": "string or empty",
  "items": [
    { "item_name": "string", "quantity": 1, "price": 0 }
  ],
  "total_amount": 0,
  "notes": "string or empty"
}`;

    const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/gemini-3.8-flash:generateContent?key=${apiKey}`;

    const payload = {
      contents: [
        {
          role: 'user',
          parts: [
            { text: prompt },
            {
              inlineData: {
                mimeType: mimeType || 'image/jpeg',
                data: cleanBase64
              }
            }
          ]
        }
      ],
      generationConfig: {
        responseMimeType: 'application/json',
        temperature: 0.1
      }
    };

    const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

    let response;
    let attempts = 0;
    const maxAttempts = 3;

    while (attempts < maxAttempts) {
      attempts++;
      response = await fetch(endpoint, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });

      if (response.ok) {
        break;
      }

      // If Google returns 503 (High Demand) or 429 (Rate limited), retry after delay
      if (response.status === 503 || response.status === 429) {
        if (attempts < maxAttempts) {
          console.warn(`Gemini returned ${response.status}. Retrying attempt ${attempts + 1}...`);
          await wait(attempts * 1500); // 1.5s then 3.0s
          continue;
        }
      }

      // If it's a 4xx client error, don't retry
      break;
    }

    if (!response.ok) {
      const errText = await response.text();
      return res.status(response.status).json({ error: `Gemini API Error: ${errText}` });
    }

    const data = await response.json();
    const candidateText = data?.candidates?.[0]?.content?.parts?.[0]?.text;
    
    if (!candidateText) {
      return res.status(502).json({ error: 'No response content generated by Gemini' });
    }

    const cleanJson = candidateText.replace(/```json/g, '').replace(/```/g, '').trim();
    const parsed = JSON.parse(cleanJson);

    return res.status(200).json(parsed);
  } catch (error) {
    console.error('OCR Backend Handler Error:', error);
    return res.status(500).json({ error: error.message || 'Internal server error processing image' });
  }
}
